version: '3'
name: pipe-fitting-webshop
services:
  app:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db